<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ToolTester.Importer</AssemblyName>
    <RootNamespace>ToolTester.Importer</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.9" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>
</Project>
