// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolTester.Infrastructure.Persistance;

#nullable disable

namespace ToolTester.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919024649_testresult")]
    partial class testresult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ToolTester.Domain.Entities.CWECatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abstraction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CWECatalogs");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.CWETestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cwe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DynamicFinding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumericalSeverity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StaticFinding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Test")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnIdFromTool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CWETestResults");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Relationssship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CWEID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OrderSpecified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oridinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedCweID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RelationsShips");
                });
#pragma warning restore 612, 618
        }
    }
}
