// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolTester.Infrastructure.Persistance;

#nullable disable

namespace ToolTester.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261002151715_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ToolTester.Domain.Entities.CWECatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abstraction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CweId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CweId")
                        .IsUnique();

                    b.ToTable("CWECatalogs");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.CWETestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cve")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DynamicFinding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumericalSeverity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RootCauseCWE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScannerFoundCWE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StaticFinding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Test")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestPathListedCWE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnIdFromTool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("ScanId", "Test");

                    b.ToTable("CWETestResults");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.CweSemanticRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bidirectional")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgrammingLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScannerRuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceCweId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCweId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceCweId", "TargetCweId", "Relationship", "ScannerRuleId", "ProgrammingLanguage", "Version")
                        .IsUnique();

                    b.ToTable("CweSemanticRules");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.JulietCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Covered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CweId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CweId")
                        .IsUnique();

                    b.ToTable("JulietCoverages");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChainId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CweId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OrderSpecified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ordinal")
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedCweID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CweId", "RelatedCweID", "Nature", "ViewId", "IsDerived")
                        .IsUnique();

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroundTruthAbstraction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroundTruthCweId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelationshipScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RootCauseCweId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RootCauseMatchesGroundTruth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RootCauseMatchesScanner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScannerAbstraction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScannerCweId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToolId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopologyDistance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopologyRelationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("ToolId");

                    b.HasIndex("ScanId", "ToolId");

                    b.HasIndex("ScanId", "GroundTruthCweId", "ScannerCweId", "RootCauseCweId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.CWETestResult", b =>
                {
                    b.HasOne("ToolTester.Domain.Entities.Scan", "Scan")
                        .WithMany("TestResults")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Report", b =>
                {
                    b.HasOne("ToolTester.Domain.Entities.Scan", "Scan")
                        .WithMany("Reports")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolTester.Domain.Entities.Tool", "Tool")
                        .WithMany("Reports")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scan");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Scan", b =>
                {
                    b.HasOne("ToolTester.Domain.Entities.Tool", "Tool")
                        .WithMany("Scans")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Scan", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Tool", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
