// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolTester.Infrastructure.Persistance;

#nullable disable

namespace ToolTester.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ToolTester.Domain.Entities.CWECatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abstraction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CWECatalogs");
                });

            modelBuilder.Entity("ToolTester.Domain.Entities.Relationssship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CWEID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OrderSpecified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oridinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedCweID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RelationsShips");
                });
#pragma warning restore 612, 618
        }
    }
}
